### ISSUE TITLE
Is it possible to train multiple motions at once

### ISSUE THREAD

**Issue by Timkeeper2018** [xupei0610/ICCGAN#1]
hey, I took a cursory look at your code, i see   envs/reference_motion.py    Line 71  : " for motion_file in self.motion_files: " 
Does this mean that I can specify multiple motions to train at the same time? If so, what would the command look like?
Thanks a lot.

**Comment by xupei0610** [comment]
Yes. Actually, we also report the performance of our implementation of multiple motion training in the paper (Table 3).
Just pass multiple motion files to the `iccgan.py` for training. For example,
`python iccgan.py walk kick --rank 0 --world_size 8`
`...`

A thing needs to pay attention to: because ICCGAN depends on given poses to decide action (next pose), it may be confused if there are multiple reference motions sharing some very close pose sequences.

**Comment by Timkeeper2018** [comment]
thanks, Your work is so cool that I'm confused as to why there are so few stars hhhhhhh
