### ISSUE TITLE
Hi, can I have the code for motion switching published?

### ISSUE THREAD

**Issue by Natsume0515** [xupei0610/ICCGAN#3]
Your work is so wonderful!

**Comment by xupei0610** [comment]
Sorry that we provide only the fundamental implementation of our approach here. 
To perform policy switch, you may need to set up an environment with multiple policy models loaded. After receiving the policy switch command (from an external controller or from an internal variable in the program),  fetch a score from the target policy's discriminator using the current state of the character and then directly take the target policy to control the character if the score is higher than a threshold. You may need to keep doing the threshold check for a few frames to ensure policy switch can happen. And, Some testing work is needed in order to find a proper value for the threshold. So, there is some engineering work that has to do to ensure the whole process works well, and thus we have not included it in this code.

We are reimplementing our approach using another physics simulator and may release the policy switch code then.

**Comment by Natsume0515** [comment]
I understand. I look forward to the release of that work. Thank you.
