### ISSUE TITLE
Trained policy

### ISSUE THREAD

**Issue by Yopla38** [xupei0610/ICCGAN#4]
Hello,

Thanks for this code, he work great !
But I can't see a trained policy when I use :
python iccgan.py walk
or all motion 
Bullet start and nothing move. 
In my case, I want to adapt code for another skeleton and I must see if my new motion file work great.
The others fonctions work perfectly
Thanks !
Yoann

**Comment by xupei0610** [comment]
To visualize a pre-trained policy, use the command:

> `python iccgan.py <motion>`

where `<motion>` is the motion name, like `kick`, `limp`, `punch`, etc.

**Comment by Yopla38** [comment]
Thanks for your response.
I do this but it doesn't work !
Bullet Gui open, model is load and nothing more...
When I stop program, it stop at time.sleep(30) in local.py (evaluate function).

**Comment by xupei0610** [comment]
It may be because the evaluator failed to find the checkpoint file. 
Try this first. It should be able to load our pre-trained policy in the folder of `policies`:

> `python iccgan.py walk --ckpt policies/walk`

If it works, try to change `policies/walk` to the checkpoint file or directory of your policy and `walk` to the corresponding motion name.
Or you can print `CHECKPOINT_FILE` in `iccgan.py` after the 32nd line to see if the checkpoint file is pointed correctly.

**Comment by Yopla38** [comment]
Ok, thanks a lot !
Is it possible to view reference motion in action  (with gravity to 0) ?

**Comment by xupei0610** [comment]
A simple way is to replace https://github.com/xupei0610/ICCGAN/blob/8bbfa4d405eac8077351e8d5d0c7fe411528dfbe/envs/__init__.py#L187-L188

with
```
            phase_ = self.ref_motion.phase(self.elapsed_time)
            if self.ref_motion.loopable and phase_ < phase:
                self.ref_motion.accumulate_cycle_offset()
                phase = phase_
            self.agent.pose = self.ref_motion.set_sim_time(self.elapsed_time)
```

It forcefully changes the character's pose without running any simulation.

**Comment by Yopla38** [comment]
Ohhh ! Perfect !
Thanks a lot for your time and for this wonderfull code !
